
[package]
name = "hkt-account-id-fuzz"
version = "0.0.0"
authors = ["hkt Inc <hello@hktprotocol.com>"]
publish = false
# Please update rust-toolchain.toml as well when changing version here:
rust-version = "1.63.0"
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
borsh = "0.9"
serde_json = "1"

[dependencies.hkt-account-id]
path = ".."

[[bin]]
name = "serde"
path = "fuzz_targets/serde.rs"
test = false
doc = false

[[bin]]
name = "borsh"
path = "fuzz_targets/borsh.rs"
test = false
doc = false
