[package]
name = "testlib"
version = "0.0.0"
authors = ["hkt Inc <hello@hktprotocol.com>"]
publish = false
# Please update rust-toolchain.toml as well when changing version here:
rust-version = "1.63.0"
edition = "2021"

[dependencies]
byteorder = "1.2"
once_cell = "1.5.2"

hkt-chain-configs = { path = "../../core/chain-configs" }
hkt-chain = { path = "../../chain/chain" }
hkt-crypto = { path = "../../core/crypto" }
hkt-primitives = { path = "../../core/primitives" }
hkt-test-contracts = { path = "../../runtime/hkt-test-contracts" }

[features]
default = []
