[package]
name = "storage-usage-delta-calculator"
version = "0.0.0"
authors = ["hkt Inc <hello@hktprotocol.com>", "Egor Kulikov <egor@hkt.org>"]
publish = false
# Please update rust-toolchain.toml as well when changing version here:
rust-version = "1.63.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "1.0"
tokio = { version = "1.16.1", features = ["macros", "rt-multi-thread"]}
tracing = "0.1.13"

hkt-chain-configs = { path = "../../core/chain-configs" }
hkt-primitives = { path = "../../core/primitives" }
node-runtime = { path = "../../runtime/runtime" }
hkt-o11y = { path = "../../core/o11y" }
