[package]
name = "hkt-stable-hasher"
version = "0.0.0"
authors = ["hkt Inc <hello@hktprotocol.com>"]
edition = "2021"
# Please update rust-toolchain.toml as well when changing version here:
rust-version = "1.63.0"
publish = false
