[package]
name = "store-validator"
version = "0.0.0"
authors = ["hkt Inc <hello@hktprotocol.com>"]
publish = false
# Please update rust-toolchain.toml as well when changing version here:
rust-version = "1.63.0"
edition = "2021"

[dependencies]
ansi_term = "0.12"
clap = { version = "3.1.6", features = ["derive"] }

hkt-chain-configs = { path = "../../core/chain-configs" }
hkt-primitives = { path = "../../core/primitives" }
hkt-store = { path = "../../core/store" }
hkt-o11y = { path = "../../core/o11y" }
hkt-chain = { path = "../../chain/chain" }
hktcore = { path = "../../hktcore" }

[dev-dependencies]
testlib = { path = "../../test-utils/testlib" }
serde_json = "1"
hkt-client = { path = "../../chain/client" }
